[package]
name = "draco-fsm"
authors = ["Logan Koester <logan@logankoester.com>"]
version = "0.1.0"
homepage = "https://smaug.dev/packages/draco-fsm"
keywords = []

# Optional:
# documentation = "https://example.com"
repository = "https://github.com/ereborstudios/draco-fsm"

# Which files do you want to be automatically required from your package.
requires = [
  "lib/set.rb",
  "lib/docile.rb",
  "lib/state_machine.rb",
  "lib/draco/fsm.rb"
]


[package.installs]
# Example
#
# <from> = <to>
# "lib/library.rb" = "app/lib/library.rb"

[dragonruby]
version = "3.8"
edition = "pro"
